document.writeln("<div id=\"header\">");
document.writeln("<div id=\"top_tool\">");
document.writeln("    <dt>");
document.writeln("      <ul>");
document.writeln("        <li><a href=\"http://www.hkzhe.com/fanxian/\" target=\"_blank\" rel=\"nofollow\" style=\"color:#f00;\">订酒店 返现金!</a></li>");
document.writeln("        <li>|</li>");
document.writeln("        <li><a href=\"http://www.zhuna.cn/help/\" target=\"_blank\" rel=\"nofollow\">帮助中心</a></li>");
document.writeln("        <li>|</li>");
document.writeln("        <li><a onclick=\"ZN.addfavor();\" href=\"javascript:;\" rel=\"nofollow\">加入收藏</a></li>");
document.writeln("        <li>|</li>");
document.writeln("        <li class=\"top_sitemap\"><a class=\"top_dh\" href=\"javascript:;\">网站导航</a>");
document.writeln("          <div class=\"top_sm_con\">");
document.writeln("            <h4>酒店</h4>");
document.writeln("            <p><a href=\"http://www.zhuna.cn/search/\" rel=\"nofollow\">酒店搜索</a>　<a href=\"http://www.zhuna.cn/findhotel/\" target=\"_blank\" rel=\"nofollow\">地图上找酒店</a><br />");
document.writeln("              <a href=\"http://www.zhuna.cn/liansuo/\">品牌连锁</a>　<a href=\"http://www.zhuna.cn/comment/\">酒店点评</a>　<a href=\"http://www.zhuna.cn/question/\">酒店问答</a><br />");
document.writeln("              <a href=\"http://www.zhuna.cn/special/\">专题活动</a>　<a href=\"http://www.zhuna.cn/findhotel/\" target=\"_blank\" rel=\"nofollow\">电子地图</a>　<a href=\"http://www.zhuna.cn/search/allcity/\">全部城市</a><br />");
document.writeln("              <a href=\"http://zhidao.zhuna.cn/\">住哪知道</a>　<a href=\"http://duanzu.zhuna.cn/\">住哪短租</a>");
document.writeln("              </p>");
document.writeln("            <h4>客户端</h4>");
document.writeln("            <p><a href=\"http://shouji.zhuna.cn/iphone.asp\" target=\"_blank\" rel=\"nofollow\">iPhone客户端</a> <a href=\"http://shouji.zhuna.cn/android.asp\" target=\"_blank\" rel=\"nofollow\">Android客户端</a><br /><a href=\"http://zhuomian.zhuna.cn/app.asp\" target=\"_blank\" rel=\"nofollow\">360APP 应用</a> &nbsp;<a href=\"http://zhuomian.zhuna.cn/\" target=\"_blank\" rel=\"nofollow\">桌面版</a> </p>");
document.writeln("            <h4>公交</h4>");
document.writeln("            <p><a href=\"http://www.zhuna.cn/gongjiao/\">线路查询</a></p>");
document.writeln("            <h4>帮助</h4>");
document.writeln("            <p style=\"border:none;\"><a href=\"http://www.zhuna.cn/help/\" rel=\"nofollow\">帮助中心</a>　<a href=\"http://www.zhuna.cn/Special/fanxian/\" rel=\"nofollow\">返现金活动</a><br />");
document.writeln("              <a href=\"http://www.zhuna.cn/help/list.php?c_id=9\" rel=\"nofollow\">如何预订</a>　<a href=\"http://www.zhuna.cn/help/list.php?c_id=33\" rel=\"nofollow\">如何点评</a>　<a href=\"http://www.zhuna.cn/help/list.php?c_id=17\" rel=\"nofollow\">如何提现</a></p>");
document.writeln("          </div>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("    </dt>");
document.writeln("  </div>  ");
document.writeln("<div id=\"logo\"><a href=\"http://www.zhuna.cn/\"><img src=\"http://tp1.znimg.com/v5/images/logo.gif\" alt=\"住哪网\" width=\"192\" height=\"52\" /></a><a href=\"http://www.zhuna.cn/Special/fanxian/\" target=\"_blank\" title=\"订酒店，返现金！\"><img src=\"http://tp1.znimg.com/v5/images/new.gif\" alt=\"订酒店返现金，最高返14%，上传酒店照片还能得50元，7日快速提现，还可团购酒店\" width=\"72\" height=\"41\" style=\"margin-left:8px;\" /></a></div>");
document.writeln("   <!-- <div id=\"logo\" style=\"float:left;width:312px;margin-right:12px;padding:0px 0 0 0;\"><a href=\"http://www.zhuna.cn/\"><img src=\"http://tp1.znimg.com/v5/images/logo.gif\" alt=\"住哪网\" width=\"192\" height=\"52\" style=\"float:left; display:inline;margin-top:28px;\" /></a><a href=\"http://www.zhuna.cn/special/5zhounian/\" target=\"_blank\" title=\"住哪网五周年，送豪礼！\"><img style=\"margin-left:8px;margin-top:5px;float:right;display:inline;\" src=\"http://www.zhuna.cn/v5/images/zhuna_logo_age5.gif\" alt=\"住哪网五周年抽奖活动，送豪礼！\" width=\"112\" height=\"86\" /></a></div>-->");
document.writeln("  <div id=\"top_center\">");
document.writeln("    <div class=\"top_srh_txt\">");
document.writeln("      <!--autocomplete-->");
document.writeln("        <input type=\"text\" autocomplete=\"off\" name=\"akey\" class=\"tip\" style=\"outline-style: none; outline-width: initial; outline-color: initial;\" id=\"akey\">");
document.writeln("        <input type=\"text\" id=\"demo-input\" name=\"blah\" style=\"display: none; \">");
document.writeln("      <!--autocomplete-->");
document.writeln("    </div>");
document.writeln("    <div class=\"top_srh_btn\">");
document.writeln("      <input type=\"button\" name=\"autocompletebutton\" id=\"autocompletebutton\" value=\"  \" class=\"top_srh_btn\" />");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("  </div>");
document.writeln("  <div id=\"top_right\" onclick=window.open(\"http://www.zhuna.cn/special/promote/\")><p>400-666<span>-</span>5511</p><p>010-61136611</p></div>");
document.writeln("  <div class=\"clearfloat\"></div>");
document.writeln("</div>");
document.writeln("<div id=\"nav\">");
document.writeln("<span class=\"new_mapico\"><img width=\"30\" height=\"18\" src=\"http://tp1.znimg.com/V5/images/new_mapico1.gif\" alt=\"新版地图找酒店\"></span>");
document.writeln("  <ul id=\"nav_main\">");
document.writeln("    <li id=\"nav_a11\"><a href=\"http://www.zhuna.cn/\">首页</a>首页</li>");
document.writeln("    <li id=\"nav_a2\"><a href=\"http://www.zhuna.cn/search/\">酒店预订</a>酒店预订</li>");
document.writeln("    <li id=\"nav_a4\"><a href=\"http://www.zhuna.cn/dianping/\">酒店点评</a>酒店点评</li> ");
document.writeln("	<li id=\"nav_a3\"><a href=\"http://tuan.zhuna.cn/\">酒店团购</a>酒店团购</li>");
document.writeln("    <li id=\"nav_a8\"><a href=\"http://jipiao.zhuna.cn/\">机票预订</a>机票预订</li>");
document.writeln("    <li id=\"nav_a7\"><a href=\"http://duanzu.zhuna.cn/\">短租公寓</a>短租公寓</li>");
document.writeln("    <li id=\"nav_a5\"><a href=\"http://www.zhuna.cn/findhotel/\" target=\"_blank\" rel=\"nofollow\">地图找酒店</a>地图找酒店</li>");
document.writeln("    ");
document.writeln("  </ul>");
document.writeln("  <div id=\"nav_user\">");
document.writeln("  	<div class=\"geili\"><img src=\"http://tp1.znimg.com/v5/images/geili.gif\" width=\"31\" height=\"19\" /></div>");
document.writeln("    <div id=\"nav_user_l\"></div>");
document.writeln("    <div id=\"login\"><a class=\"right_arrow\" href=\"http://passport.zhuna.cn/user/login.asp\">登录</a> ");
document.writeln("      <div id=\"loginbox\">");
document.writeln("        <div method=\"dvlogin\" class=\"logon\">");
document.writeln("          <ul>");
document.writeln("            <li>手机：");
document.writeln("              <input type=\"text\" value=\"\" name=\"username\" id=\"username\" class=\"login_text\" />");
document.writeln("            </li>");
document.writeln("            <li>密码：");
document.writeln("              <input type=\"password\" value=\"\" class=\"login_text\" name=\"password\" id=\"password\" />");
document.writeln("            </li>");
document.writeln("            <li style=\"padding-left:36px\"><input type=\"checkbox\" name=\"expires\" id=\"expires\" class=\"checkbox\"><label for=\"expires\">30天免登录</label></li>");
document.writeln("            <!--获取焦点时type=\"password\"-->");
document.writeln("            <li class=\"clx\"> <span method=\"wait\" style=\"display:none\" class=\"right\">");
document.writeln("              <input type=\"button\" value=\" \" class=\"login_btn logining\">");
document.writeln("              </span><span method=\"login\">");
document.writeln("              <input type=\"button\" method=\"login\" value=\"登 录\" class=\"login_btn\">");
document.writeln("              </span></li>");
document.writeln("            <li class=\"clx\"><a title=\"注册住哪网帐号可快速预订并获得10元现金\" class=\"right\" href=\"http://passport.zhuna.cn/user/reg.asp\" rel=\"nofollow\">还没有帐号?</a>&nbsp;&nbsp;&nbsp;<a href=\"http://passport.zhuna.cn/user/lostpassword.asp\" target=\"_blank\" rel=\"nofollow\">忘记密码?</a></li>");
document.writeln("            <li style=\"border-top:1px solid #CCCCCC; padding-bottom:3px\">使用合作网站账号登录</li>");
document.writeln("          <li class=\"l_share\" style=\"margin-bottom:5px;\"><a href=\"javascript:;\" onclick=\"ZN.login.oAuth(\'WEIBOSN\',this,\'self\');\" class=\"sina_share\">新浪微博登录</a><a href=\"javascript:;\" onclick=\"ZN.login.oAuth(\'QQ\',this,\'self\');\" class=\" qq_share \">QQ登录</a><a href=\"javascript:;\" onclick=\"ZN.login.oAuth(\'RENREN\',this,\'self\');\" class=\"rr_share\">人人网登录</a><a href=\"javascript:;\" onclick=\"ZN.login.oAuth(\'WEIBOTX\',this,\'self\');\" class=\" kj_share\">腾讯微博登录</a></li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div id=\"u_reg\"><a href=\"http://www.hkzhe.com/member.php?mod=register\" rel=\"nofollow\">免费注册</a></div>");
document.writeln("    <div id=\"account\"><a class=\"right_arrow\" href=\"javascript:;\">我的账户</a>");
document.writeln("      <div id=\"nav_user_menu\">");
document.writeln("        <ul>");
document.writeln("          <li><a href=\"http://www.zhuna.cn/user/\" rel=\"nofollow\">会员中心</a></li>");
document.writeln("          <li><a href=\"http://www.zhuna.cn/user/formlist.asp\" rel=\"nofollow\">酒店订单</a></li>");
document.writeln("          <li><a href=\"http://tuan.zhuna.cn/order/index.php\" rel=\"nofollow\">我的团购</a></li>");
document.writeln("          <li><a href=\"http://www.zhuna.cn/user/mycomment.asp\" rel=\"nofollow\">我的点评</a></li>");
document.writeln("          <li><a href=\"http://www.zhuna.cn/user/myhotel.asp\" rel=\"nofollow\">常住酒店</a></li>");
document.writeln("          <li><a href=\"http://jipiao.zhuna.cn/User/index\" rel=\"nofollow\">我的机票</a></li>");
document.writeln("          <li><a href=\"http://www.zhuna.cn/user/favorites.asp\" rel=\"nofollow\">收藏酒店</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</div>");